version: "3.8"

services:
  app:
    build: .
    container_name: contato-seguro-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - contato-seguro-network

networks:
  contato-seguro-network:
    driver: bridge
